{% set name = "pytesseract" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/madmaze/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1de64cae604fc0b2bc5b185620c612199b01c833c64c2a4a9e8877ace1ed5a92

build:
  number: 0
  # Currently tesseract isn't available on win-64
  skip: True  # [py<37 or win]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytesseract = pytesseract.pytesseract:main

requirements:
  host:
    - python
    - pip
    - setuptools >=40.0.4
    - wheel >=0.29.0
  run:
    - python
    - pillow >=8.0.0
    - packaging >=21.3
    - tesseract

test:
  imports:
    - PIL
    - PIL.Image
    - pytesseract
  files:
    - eurotext.tif
  requires:
    - pip
    # py-opencv is needed for the test command
    - py-opencv
  commands:
    - python -m pip check
    - echo "Test CLI usage:" && pytesseract -l eng eurotext.tif 
    - echo "Test pytesseract library usage:" && python -c "from PIL import Image; import pytesseract; print(pytesseract.image_to_string(Image.open('eurotext.tif')))"

about:
  home: https://github.com/madmaze/pytesseract
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python-tesseract is an optical character recognition (OCR) tool for python.

  description: |
    Python-tesseract is a wrapper for Google's Tesseract-OCR Engine.
    It is also useful as a stand-alone invocation script to tesseract,
    as it can read all image types supported by the Pillow and Leptonica
    imaging libraries, including jpeg, png, gif, bmp, tiff, and others.
    Additionally, if used as a script, Python-tesseract will print the
    recognized text instead of writing it to a file
  dev_url: https://github.com/madmaze/pytesseract
  doc_url: https://github.com/madmaze/pytesseract/blob/master/README.rst


extra:
  recipe-maintainers:
    - mxr-conda
    - adbeda
    - agcopenhaver
    - int3l
    - oblute
    - rluria14
