{% set name = "pytesseract" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/madmaze/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 155dee89cae8de07dffe94d3ad96bbdbb6a486943fb283c169f5f35c9d4963b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytesseract = pytesseract.pytesseract:main

requirements:
  build:
    - python
    - pip


  run:
    - python
    - flake8
    - pep8-naming
    - flake8-quotes
    - pytest
    - pillow

test:
  imports:
    - PIL
    - PIL.Image
    - pytesseract


about:
  home: https://github.com/madmaze/pytesseract
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python-tesseract is an optical character recognition (OCR) tool for python.

  description: |
    Python-tesseract is a wrapper for Google's Tesseract-OCR Engine.
    It is also useful as a stand-alone invocation script to tesseract,
    as it can read all image types supported by the Pillow and Leptonica
    imaging libraries, including jpeg, png, gif, bmp, tiff, and others.
    Additionally, if used as a script, Python-tesseract will print the
    recognized text instead of writing it to a file


extra:
  recipe-maintainers:
    - adbeda
    - agcopenhaver
    - int3l
    - oblute
    - rluria14
