travis:
  secure:
    BINSTAR_TOKEN: h1LJU0waXW2nSSkN93fwWZJOSo9MQIAQJLErayLyEw3bSup2VkC/Axl6/xTJYJKos71b8lgr49AyFdMdvG0ew7GpIxKDzEqEpZW7Ll5wC0xMFizdC0p6ob2UNliyl+u+Z1C514cxaQI1Snwyfjhx5qLl3HJTlxrEYrBiw7DjMcgjqfudm5DvpYTPVq6ioonH+aqTe6fHVWyGFVsfcPBQCNUl2Xo7XJvatlmzgvQgB+2O5BQg9eONhbp20GpSKuaDDYRdeRqwjx+t6GJGCjbH1EyGFvYItQgL9BkAjDXTzWXn99d9ukwN1vJ6qK8x2121bPVlFSjrNlN5OLWHF0GgjVOhin8klPbWJESDOMKKaGWUfoSOnS6o6F/cll4aZ9KEtgm6nuMfODisPOZxK29R3PGfSk7EjxljcC7UGdikaXyfqyoNpUsXxwgOkpinTXoht+0mHksnMRElt0xzrwXOqc5f2CoqujJxDNHYT+43qLGw2aKxBj+v/vtLzfk3x9ZGDfuhAQ8LfdN5ewRXRcIpi9sxsPoLeBT3IrIa7VYeYEjrP7AyJJpI+FP/tTPuQbTyWKKdX6F32U+2voTArxLVMoxoiexy6XDNQ2FZgZRp8irDBXJsMdpKbEfxPN9nfgpm4ztyimkEaCQ9rm81bfQdWxo4FeRaHs9KV+TWWE0OL8U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
